# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrczframe(wx.Frame):
#!XRCED:begin-block:xrczframe.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrczframe.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "zframe")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.btn_next = xrc.XRCCTRL(self, "btn_next")

        self.Bind(wx.EVT_BUTTON, self.OnButton_btn_next, self.btn_next)
        self.Bind(wx.EVT_KEY_DOWN, self.OnKey_down_btn_next, self.btn_next)

#!XRCED:begin-block:xrczframe.OnButton_btn_next
    def OnButton_btn_next(self, evt):
        # Replace with event handler code
        print "OnButton_btn_next()"
        self.txt_main = xrc.XRCCTRL(self, "txt_main")
        self.txt_main.SetValue("你好")
#!XRCED:end-block:xrczframe.OnButton_btn_next        

#!XRCED:begin-block:xrczframe.OnKey_down_btn_next
    def OnKey_down_btn_next(self, evt):
        # Replace with event handler code
        print "OnKey_down_btn_next()"
#!XRCED:end-block:xrczframe.OnKey_down_btn_next        




# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    hello_xrc = '''\
<?xml version="1.0" ?><resource class="wxButton">
  <object class="wxFrame" name="zframe">
    <object class="wxBoxSizer">
      <orient>wxHORIZONTAL</orient>
      <object class="sizeritem">
        <object class="wxTextCtrl" name="txt_main">
          <size>300,300</size>
          <value>hello</value>
          <style>wxTE_AUTO_SCROLL|wxTE_MULTILINE</style>
        </object>
        <option>4</option>
        <flag>wxEXPAND</flag>
        <border>2</border>
      </object>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <orient>wxVERTICAL</orient>
          <object class="sizeritem">
            <object class="wxButton" name="btn_next">
              <label>下一个</label>
              <XRCED>
                <events>EVT_BUTTON|EVT_KEY_DOWN</events>
                <assign_var>1</assign_var>
              </XRCED>
            </object>
          </object>
        </object>
      </object>
    </object>
    <title>你好</title>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/hello/hello_xrc', hello_xrc)
    __res.Load('memory:XRC/hello/hello_xrc')


# ----------------------- Gettext strings ---------------------

def __gettext_strings():
    # This is a dummy function that lists all the strings that are used in
    # the XRC file in the _("a string") format to be recognized by GNU
    # gettext utilities (specificaly the xgettext utility) and the
    # mki18n.py script.  For more information see:
    # http://wiki.wxpython.org/index.cgi/Internationalization 
    
    def _(str): pass
    
    _("hello")
    _("下一个")
    _("你好")

