# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcidf_main(wx.Frame):
#!XRCED:begin-block:xrcidf_main.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcidf_main.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "idf_main")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers



class xrcidc_main_menubar(wx.MenuBar):
    def __init__(self):
        pre = get_resources().LoadMenuBar("idc_main_menubar")
        self.PostCreate(pre)
        
        # Define variables for the menu items



class xrcidc_main_toolbar(wx.ToolBar):
    def __init__(self, parent):
        pre = get_resources().LoadToolBar(parent, "idc_main_toolbar")
        self.PostCreate(pre)
        
        # Define variables for the toolbar items



class xrcidd_new(wx.Dialog):
#!XRCED:begin-block:xrcidd_new.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcidd_new.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "idd_new")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    main_xrc = '''
'''

    wx.MemoryFSHandler.AddFile('main.xrc', main_xrc)
    __res.Load('memory:main.xrc')


# ----------------------- Gettext strings ---------------------

def __gettext_strings():
    # This is a dummy function that lists all the strings that are used in
    # the XRC file in the _("a string") format to be recognized by GNU
    # gettext utilities (specificaly the xgettext utility) and the
    # mki18n.py script.  For more information see:
    # http://wiki.wxpython.org/index.cgi/Internationalization 
    
    def _(str): pass
    
    _("IDL Job Manager")
    _("Jobs")
    _("Hosts")
    _("Jobs")
    _("Hosts")
    _("Details")
    _("Output")
    _("Errors")
    _("Master")
    _("&File")
    _("&New")
    _("E&xit")
    _("&Admin")
    _("&Run Queue")
    _("&Pause Queue")
    _("Resu&me Queue")
    _("&Options")
    _("&Login...")
    _("Lo&gout")
    _("&Job")
    _("&Submit Job")
    _("Sus&pend Job")
    _("Resu&me Job")
    _("&CancelJob")
    _("Sho&w")
    _("&Refresh")
    _("&Vertical Arrangement")
    _("&Help")
    _("&Index")
    _("&About ...")
    _("&New")
    _("New Job")
    _("New Job")
    _("New Job")
    _("Text Mode")
    _("resize -v2 -i L:/images/Kyle/Nasa1 -i L:/images/Kyle/Violin w=512 h=389")
    _("category1")
    _("Option1:")
    _("value")
    _("Option1:")
    _("value")
    _("Option1:")
    _("value")
    _("category2")
    _("General")
    _("Job Name:")
    _("NEWJOB1")
    _("Owner:")
    _("NEWOWNER1")
    _("Submit Job &Immediately")
    _("&OK")
    _("&Cancel")
    _("&Apply")



__init_resources()
app = wx.PySimpleApp()
frm1 = xrcidf_main(parent=None)
#frm2 = UNTITLED_xrc.xrcFRAME2(parent=None)
frm1.Show()
#frm2.Show()
app.MainLoop()
