# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcmframe(wx.Frame):
#!XRCED:begin-block:xrcmframe.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcmframe.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "mframe")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.btnabout = xrc.XRCCTRL(self, "btnabout")

        self.Bind(wx.EVT_BUTTON, self.OnButton_btnsearch, id=xrc.XRCID('btnsearch'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_btnsave, id=xrc.XRCID('btnsave'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_btnabout, self.btnabout)
        self.Bind(wx.EVT_KEY_DOWN, self.OnKey_down_btnabout, self.btnabout)

#!XRCED:begin-block:xrcmframe.OnButton_btnsearch
    def OnButton_btnsearch(self, evt):
        print 'parent:OnButton_btnsearch'
        
        
#!XRCED:end-block:xrcmframe.OnButton_btnsearch        

#!XRCED:begin-block:xrcmframe.OnButton_btnsave
    def OnButton_btnsave(self, evt):
        # Replace with event handler code
        print "OnButton_btnsave()"
#!XRCED:end-block:xrcmframe.OnButton_btnsave        

#!XRCED:begin-block:xrcmframe.OnButton_btnabout
    def OnButton_btnabout(self, evt):
        # Replace with event handler code
        print "OnButton_btnabout()"
#!XRCED:end-block:xrcmframe.OnButton_btnabout        

#!XRCED:begin-block:xrcmframe.OnKey_down_btnabout
    def OnKey_down_btnabout(self, evt):
        # Replace with event handler code
        print "OnKey_down_btnabout()"
#!XRCED:end-block:xrcmframe.OnKey_down_btnabout        




# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    __res.Load('main.xrc')

# ----------------------- Gettext strings ---------------------

def __gettext_strings():
    # This is a dummy function that lists all the strings that are used in
    # the XRC file in the _("a string") format to be recognized by GNU
    # gettext utilities (specificaly the xgettext utility) and the
    # mki18n.py script.  For more information see:
    # http://wiki.wxpython.org/index.cgi/Internationalization 
    
    def _(str): pass
    
    _("Search(&F)")
    _("hello,ABC")
    _("&Save")
    _("&About")
    _("http://blog.csdn.net/ablo&zhou")
    _("I Love ABC")

