# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcmframe(wx.Frame):
#!XRCED:begin-block:xrcmframe.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcmframe.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "mframe")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.btnnext = xrc.XRCCTRL(self, "btnnext")

        self.Bind(wx.EVT_MENU, self.OnMenu_open, id=xrc.XRCID('open'))
        self.Bind(wx.EVT_MENU, self.OnMenu_save, id=xrc.XRCID('save'))
        self.Bind(wx.EVT_MENU, self.OnMenu_exit, id=xrc.XRCID('exit'))
        self.Bind(wx.EVT_MENU, self.OnMenu_paste, id=xrc.XRCID('paste'))
        self.Bind(wx.EVT_TOOL, self.OnTool_open, id=xrc.XRCID('open'))
        self.Bind(wx.EVT_TREE_SEL_CHANGED, self.OnTree_sel_changed_tree, id=xrc.XRCID('tree'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_btnnext, self.btnnext)
        self.Bind(wx.EVT_KEY_DOWN, self.OnKey_down_btnnext, self.btnnext)
        self.Bind(wx.EVT_BUTTON, self.OnButton_btnsave, id=xrc.XRCID('btnsave'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_btnsearch, id=xrc.XRCID('btnsearch'))

#!XRCED:begin-block:xrcmframe.OnMenu_open
    def OnMenu_open(self, evt):
        # Replace with event handler code
        print "OnMenu_open()"
#!XRCED:end-block:xrcmframe.OnMenu_open        

#!XRCED:begin-block:xrcmframe.OnMenu_save
    def OnMenu_save(self, evt):
        # Replace with event handler code
        print "OnMenu_save()"
#!XRCED:end-block:xrcmframe.OnMenu_save        

#!XRCED:begin-block:xrcmframe.OnMenu_exit
    def OnMenu_exit(self, evt):
        # Replace with event handler code
        print "OnMenu_exit()"
#!XRCED:end-block:xrcmframe.OnMenu_exit        

#!XRCED:begin-block:xrcmframe.OnMenu_paste
    def OnMenu_paste(self, evt):
        # Replace with event handler code
        print "OnMenu_paste()"
#!XRCED:end-block:xrcmframe.OnMenu_paste        

#!XRCED:begin-block:xrcmframe.OnTool_open
    def OnTool_open(self, evt):
        # Replace with event handler code
        print "OnTool_open()"
#!XRCED:end-block:xrcmframe.OnTool_open        

#!XRCED:begin-block:xrcmframe.OnTree_sel_changed_tree
    def OnTree_sel_changed_tree(self, evt):
        # Replace with event handler code
        print "OnTree_sel_changed_tree()"
#!XRCED:end-block:xrcmframe.OnTree_sel_changed_tree        

#!XRCED:begin-block:xrcmframe.OnButton_btnnext
    def OnButton_btnnext(self, evt):
        # Replace with event handler code
        print "OnButton_btnnext()"
#!XRCED:end-block:xrcmframe.OnButton_btnnext        

#!XRCED:begin-block:xrcmframe.OnKey_down_btnnext
    def OnKey_down_btnnext(self, evt):
        # Replace with event handler code
        print "OnKey_down_btnnext()"
#!XRCED:end-block:xrcmframe.OnKey_down_btnnext        

#!XRCED:begin-block:xrcmframe.OnButton_btnsave
    def OnButton_btnsave(self, evt):
        # Replace with event handler code
        print "OnButton_btnsave()"
#!XRCED:end-block:xrcmframe.OnButton_btnsave        

#!XRCED:begin-block:xrcmframe.OnButton_btnsearch
    def OnButton_btnsearch(self, evt):
        print 'parent:OnButton_btnsearch'
        
        
#!XRCED:end-block:xrcmframe.OnButton_btnsearch        




# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    __res.Load('main.xrc')

# ----------------------- Gettext strings ---------------------

def __gettext_strings():
    # This is a dummy function that lists all the strings that are used in
    # the XRC file in the _("a string") format to be recognized by GNU
    # gettext utilities (specificaly the xgettext utility) and the
    # mki18n.py script.  For more information see:
    # http://wiki.wxpython.org/index.cgi/Internationalization 
    
    def _(str): pass
    
    _("&Open")
    _("&File")
    _("&Save")
    _("&Exit")
    _("&Edit")
    _("&Paste")
    _("&Help")
    _("&Index")
    _("hello,ABC")
    _("&Next")
    _("&Save")
    _("Search(&F)")
    _("I Love ABC")

